services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      DEBUG: true
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - inventro-network

  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - inventro:/app/inventro
    networks:
      - inventro-network
    entrypoint: ["sh", "entrypoint.sh"]
  
volumes:
  pgdata:
  inventro:

networks:
  inventro-network:
    driver: bridge