# Generated by Django 5.2.8 on 2025-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
