# Generated by Django 5.2.8 on 2025-12-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10, null=True),
        ),
    ]
